### ISSUE TITLE
Setting Environment Variables

### ISSUE THREAD

**Issue by Mitchello457** [ClarkMcGrew/edep-sim#36]
I have installed edep-sim using the Expert Installation instructions as I wanted a custom install location. Your installation instructions to not include what environmoent variables are needed to run the software. I added the `bin/` directory to my path so I can run the `edep-sim` command but now I am seeing the following error:
```
edep-sim: error while loading shared libraries: libedepsim.so: cannot open shared object file: No such file or directory
```

Is there an environment variable along the lines of `$EDEPSIM_LIBRARY_PATH` I need to have pointing to `libedepsim.so`? If so, are there any other environment variables that I need for the installation to work? These things should be included in the `README.md`.

**Comment by ClarkMcGrew** [comment]
Hi Mitchell,

This is a classic "works for me" situation, so I'm not sure. It's 
suppose to be a very standard cmake build.

Off the top of my head, you might need to set LD_LIBRARY_PATH which is 
the unix shared library search path.  Another thing you could try would 
be to run ldd on the executable and see if it's giving any hints.

Cheers,

Clark

**Comment by Mitchello457** [comment]
Adding `lib/` from the install directory to the `LD_Library_PATH` fixed my issue. Thank you for the assistance!
